### ISSUE TITLE
App crash in iOS Device

### ISSUE THREAD

**Issue by rajan1910** [AuthorizeNet/accept-sample-ios#11]
Hello all,
I had integrated "AuthorizeNetAccept" in my project. It was working fine in simulator as well as in real device but now it crash when I want to create object for "AcceptSDKCardFieldsValidator" as well as "AcceptSDKHandler" class.

My project is in swift 2.3. Can anyone please help me out in this??
@brianmc can you please help me out in this?

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.
