### ISSUE TITLE
Success but no charge

### ISSUE THREAD

**Issue by bmhdev** [AuthorizeNet/accept-sample-ios#12]
Using this code I see a successful token bit I don't see how to submit the opaque data to authorize.net to actually charge the card

**Comment by brianmc** [comment]
You can plug it right in here:  http://developer.authorize.net/api/reference/index.html#mobile-inapp-transactions

**Comment by bmhdev** [comment]
That method doesn't use the opaque data however the Create Apple Pay Transaction does.  Also I see how to send via json, however does anyone have doe for iOS and swift

**Comment by brianmc** [comment]
You should never do the payment transaction from a phone or any client device.  Always from a server.

**Comment by bmhdev** [comment]
I see.  I must have missed that.  So once the opaqueData is received, I would send this over to my server using ssl and have node or c# code to accept that token and pass it to Auth.net.  Lastly, return the success/failure to the client.  Looks like there are some examples on the GitHub for the client-side piece as well.

**Comment by RakeshVisa** [comment]
Hi @bmhdev, hope you are able to use the accept-sdk-ios. As of now we are closing this issue, in case if you need further assistance please write to us and we are happy to help you.
