### ISSUE TITLE
[iOS][Swift] Cannot import module AuthorizeNetAccept

### ISSUE THREAD

**Issue by taquocy** [AuthorizeNet/accept-sample-ios#13]
After I run successfully your sample app. Then I decide to mere source from it to my project.
I install successully your module via command pod 'AuthorizeNetAccept' and copy/ paste the 'ViewController.swift' file + your ViewController to my story board.
But when I build, I met the issue 'No such module AuthorizeNetAccept' at import statement. Can you give me the step by step to resolve this issue.
Thanks.

**Comment by arjavlad** [comment]
Having the same issue here.

**Comment by Karanjks** [comment]
Hi @arjavlad  & @taquocy have got the solution??? pls help me...

**Comment by RakeshVisa** [comment]
Hi @Karanjks, @arjavlad, We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.
