### ISSUE TITLE
"The element 'createTransactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'refId' in namespace 

### ISSUE THREAD

**Issue by Junaidtt** [AuthorizeNet/accept-sample-ios#15]
Getting error response while making payment , how can I solve this?Any help please

Request :

[
"createTransactionRequest":
["refId": "123456",
"transactionRequest":
["payment": ["opaqueData": ["dataDescriptor": "COMMON.ACCEPT.INAPP.PAYMENT", "dataValue": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="]],
"shipTo": ["state": "TX", "city": "Pecan Springs", "zip": "44628", "address": "12 Main Street", "lastName": "Bayles", "firstName": "China", "company": "Thyme for Tea", "country": "USA"], "userFields": ["userField": [["name": "MerchantDefinedFieldName1", "value": "MerchantDefinedFieldValue1"], ["name": "favorite_color", "value": "blue"]]], "poNumber": "456654", "billTo": ["state": "TX", "city": "Pecan Springs", "zip": "44628", "address": "14 Main Street", "lastName": "Johnson", "firstName": "Ellen", "company": "Souveniropolis", "country": "USA"], "transactionType": "authCaptureTransaction", "lineItems": ["lineItem": ["itemId": "1", "name": "vase", "description": "Cannes logo", "quantity": "18", "unitPrice": "45.00"]], "amount": "1", "customerIP": "192.168.1.1"],

"merchantAuthentication":
["name": "xxxxxxxxxxx", "transactionKey": "xxxxxxxxxxxxx"]
]
]

Response:

{
messages = {
message = (
{
code = E00003;
text = "The element 'createTransactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'refId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'merchantAuthentication' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.";
}
);
resultCode = Error;
};
}

**Comment by deepaksinghnegi** [comment]
Hi @Junaidtt, Have you got any success implementing this? I'm having the same issue.

**Comment by Junaidtt** [comment]
Yes, Firstly referring  Codable will give you more idea.

struct Transaction: Codable {
    let createTransactionRequest: CreateTransactionRequest
}
struct CreateTransactionRequest: Codable {
    let merchantAuthentication: MerchantAuthentication
    let refId: String
    let transactionRequest: TransactionRequest
}
struct MerchantAuthentication: Codable {
    let name: String
    let transactionKey: String
}
struct TransactionRequest: Codable {
    let transactionType: String
    let amount: String
    let payment: Payment
}
struct Payment: Codable {
    let opaqueData: OpaqueData
}
struct OpaqueData: Codable {
    let dataDescriptor: String
    let dataValue: String
}

You will be more clear on this Stackoverflow question.
[](https://stackoverflow.com/questions/47478549/order-of-json-node-changes-while-making-post-request-swift)

**Comment by deepaksinghnegi** [comment]
Thanks for replying. Actually I've already  done the same but getting following json object:
["createTransactionRequest": {
	merchantAuthentication = {
		name = "";
		transactionKey = "";
	};
	refId = "123456";
	transactionRequest = {
		amount = 20;
		payment = {
			opaqueData = {
				dataDescriptor = "COMMON.ACCEPT.INAPP.PAYMENT";
				dataValue = "";
			};
		};
		transactionType = authCaptureTransaction;
	};
}]

Here I'm getting  transactionType in wrong place(I think its alphabetical in order). Can you please help me fix this issue.

**Comment by otjutt** [comment]
I solved a similar problem of mine by using the exact ordering of keys as present in the documentation.

**Comment by Housi** [comment]
> I solved a similar problem of mine by using the exact ordering of keys as present in the documentation.

yes this works, thanks!
