### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2:

### ISSUE THREAD

**Issue by meetdoshi1992** [AuthorizeNet/accept-sample-ios#16]
![screen shot 2017-12-23 at 3 01 45 pm](https://user-images.githubusercontent.com/7357932/34318597-30af9f80-e7f2-11e7-8cb8-c39fb9bb0869.png)
I am getting this error :

Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2:

How can I resolve this error.?

**Comment by Beautistar** [comment]
Same issue with me..
Please let me know how can use AuthorizeNet in iOS lastest swift version
Thanks

**Comment by ckpiggy** [comment]
+ 1

**Comment by laraibmaliknew** [comment]
same issue I m facing

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us. Also please refer the latest sample code base for the usage of accept-sdk-ios
