### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by vivekfarshore** [AuthorizeNet/accept-sample-ios#17]
What needs to be done with the base64 converted string next, Please provide us with the next step guide through the AuthorizeNet as illustrated here
https://github.com/AuthorizeNet/accept-sample-ios/blob/master/AcceptSDKSampleApp/ApplePayViewController.swift

**Comment by RakeshVisa** [comment]
You can plug it right in here:  http://developer.authorize.net/api/reference/index.html#mobile-inapp-transactions. Let us know if you need further assistance.

**Comment by RakeshVisa** [comment]
Hi @vivekfarshore, i hope you are able to get the solution that you are looking for. Please let us know if you need any further assistance.
