### ISSUE TITLE
Swift 4.1

### ISSUE THREAD

**Issue by mohammadkalim** [AuthorizeNet/accept-sample-ios#18]
Kindly update the package for swift 4.1, Getting error in the package it's compiled on swift 4.0.1

Kindly update it. need urgent request to build 

Thanking in advance.

**Comment by yuyongmao** [comment]
i meet the same question and use cocoapods get the accpet sdk 0.20 and bulid success run crashed

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.
