### ISSUE TITLE
Error - E00001, Unexpected character encountered

### ISSUE THREAD

**Issue by deepaksinghnegi** [AuthorizeNet/accept-sample-ios#19]
I'm working on Authorize.net payment api and while making transaction request as follows:

`let json =  """
    {
      "createTransactionRequest": {
        "merchantAuthentication": {
          "name": "",
          "transactionKey": ""
          },
        "refId": "2",
        "transactionRequest": {
          "transactionType": "authCaptureTransaction",
          "amount": "\(totalAmount)",
        "payment": {
          "opaqueData": {
            "dataDescriptor": "\(inResponse.getOpaqueData().getDataDescriptor())",
            "dataValue": "\(inResponse.getOpaqueData().getDataValue())"
            }
          }
        }
      }
    }
    """

    let jsonData = Data(json.utf8)
    do {
      let transaction = try JSONDecoder().decode(Transaction.self, from: jsonData)
      print(transaction)
      // encoding
      let encodedData = try JSONEncoder().encode(transaction)
      print(String(data: encodedData, encoding: .utf8)!)

      //Data to [String : Any]
      do {
        let params = try JSONSerialization.jsonObject(with: encodedData, options: []) as! [String: Any]
        print(params)
        Alamofire.request(“https://apitest.authorize.net/xml/v1/request.api”, method: .post, parameters: params).responseJSON {response in
          print(response)
        }
      } catch {
        print(error)
      }
`

getting following error

`error  {
   messages =     {
       message =         (
                       {
               code = E00001;
               text = "Unexpected character encountered while parsing value: c. Path '', line 0, position 0.";
           }
       );
       resultCode = Error;
   };
} 
`
Is my approach of implementation correct? Please help.

**Comment by shankar101** [comment]
is it solve?

**Comment by mayurmakwanaais** [comment]
same error occur while ajax with given demo example request set then also didn't  work
